version: '3.5'

networks:
  backend:
    driver: bridge
volumes:
  mysql:
    driver: local

services:
### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=5.7
      environment:
        - MYSQL_DATABASE=todo4
        - MYSQL_ROOT_PASSWORD=root
        - TZ=UTC
      volumes:
        - ~/.laradock/data/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
      networks:
        - backend
